name: CI

on:
  push:
    branches:
    - main

jobs:
  build_and_test:
    name: Test Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.8', '3.9']
    env:
      PYTHONDEVMODE: 1

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

    - name: Poetry setup
      run: |
        python -m pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Lint with mypy
      run: |
        poetry run mypy gamatrix

    - name: Lint with flake8
      run: |
        poetry run flake8

    - name: Format with Black
      run: |
        poetry run black --check .

    - name: Test with pytest
      run: |
        poetry run pytest --cov
